[tools]
wasm_bindgen = "0.2.87"

# workaround: loads the wasm file and adds the bindings 
# to window.wasm for access within js
# https://github.com/thedodd/trunk/issues/298
[build]
pattern_script = "<script type=\"module\">import init, * as with_bindings from '{base}{js}';init('{base}{wasm}').then(()=>window.wasm=with_bindings);</script>"

[watch]
ignore = [".webpack", "src/wfc-web.d.ts"]

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss","-o","./tailwind.css"]

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["webpack", "--config", "webpack.config.js"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "mv $TRUNK_STAGING_DIR/wfc-web-*.d.ts $TRUNK_SOURCE_DIR/src/wfc-web.d.ts"]
